title: John Collandra
description: Personal Portfolio
author: John Collandra
email: jpcollandra@gmail.com
phone: (904) 452-8608
github: https://github.com/jpcollandra
about: I am a developer with a passion for data science and cyber secuirty. I consider myself full stack capable
disqus_shortname: programming
google_analytics:
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/john.collandra"
    - icon: fa-twitter
      link: "https://twitter.com/jpakjr"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/tauseef-jamadar-5b577913/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/tmjam"

share:
  twitter_username: tmjam3011
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://tmjam.github.io/tauseef-blog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
